#rm -rf build
mkdir build
cd build
cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install -DBUILD_EXECUTABLE=ON -DF2F_NO_CUDA=ON -DENABLE_CUDA=OFF -DWITH_IMGUI=ON -DFACE_TOOLKIT=OFF
make -j
